(() => {
  const weatherByProvince = new Map(); let selectedProvince = PROVINCES[0]; let selectedPlace = { name: "Kabul", country: "Afghanistan", timezone: "Asia/Kabul", latitude: 34.5553, longitude: 69.2075, id: "kabul" }; let activeData = null; let provinceQuery = ""; let loadSequence = 0; const queue = []; const loadingIds = new Set(); let running = 0; let observer = null;
  function statusFor(error) { const code = error?.code; if (!navigator.onLine || code === "NETWORK") return [t("offline"), "offline"]; if (code === "RATE_LIMIT") return [t("rate"), "rate"]; if (code === "INVALID_LOCATION" || code === "NOT_FOUND") return [t("notFound"), "error"]; return [t("apiError"), "error"]; }
  function drawProvinces() { const focusedId = document.activeElement?.dataset?.provinceId; observer?.disconnect(); renderProvinceCards(provinceQuery, weatherByProvince, selectedProvince?.id); if (focusedId) [...document.querySelectorAll(".province-card")].find(card => card.dataset.provinceId === focusedId)?.focus({ preventScroll: true }); observeCards(); }
  async function loadPlace(place, province = null) { const requestId=++loadSequence;selectedPlace = place; selectedProvince = province; activeData = null; storageSet("weather-location", JSON.stringify({ name: place.name, country: place.country || "", region: place.region || "", timezone: place.timezone || "UTC", latitude: place.latitude, longitude: place.longitude, id: province?.id || null })); if (province) weatherByProvince.set(province.id, null); drawProvinces(); renderWeatherLoading(province ? { ...province, country: t("country") } : place); setStatus(t("loading"), "loading"); try { const data = await getWeather(place.latitude, place.longitude);if(requestId!==loadSequence)return; activeData = data; data.locationName = place.name; data.region = place.region || ""; if (province) weatherByProvince.set(province.id, data); renderWeather(data, province ? { ...province, country: t("country") } : place); drawProvinces(); setStatus(""); } catch (error) {if(requestId!==loadSequence)return; const saved = getAnyStoredWeather(place.latitude, place.longitude); if (saved) { activeData = saved.data; activeData.locationName = place.name; if (province) weatherByProvince.set(province.id, activeData); renderWeather(activeData, province ? { ...province, country: t("country") } : place, { stale: true }); drawProvinces(); setStatus(t("stale"), "stale"); return; } renderWeatherUnavailable(); const [message, state] = statusFor(error); setStatus(message, state); } }
  function selectProvince(province) { const place = { name: province.capital, country: t("country"), region: currentLanguage === "fa" ? province.nameFa : province.nameEn, timezone: "Asia/Kabul", latitude: province.latitude, longitude: province.longitude, id: province.id }; loadPlace(place, province); document.querySelector(".weather-hero").scrollIntoView({ behavior: matchMedia("(prefers-reduced-motion: reduce)").matches ? "auto" : "smooth", block: "start" }); }
  function enqueueProvince(province) { if (province.id === selectedProvince?.id || weatherByProvince.has(province.id) || loadingIds.has(province.id)) return; loadingIds.add(province.id); queue.push(province); processQueue(); }
  async function processQueue() { while (running < 2 && queue.length) { const province = queue.shift(); running++; try { const data = await getWeather(province.latitude, province.longitude); data.locationName = province.capital; weatherByProvince.set(province.id, data); } catch { weatherByProvince.set(province.id, { error: true }); } finally { running--; loadingIds.delete(province.id); drawProvinces(); } } }
  function observeCards() { if (!("IntersectionObserver" in window)) { PROVINCES.forEach(enqueueProvince); return; } if (!observer) observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { const province = PROVINCES.find(item => item.id === entry.target.dataset.provinceId); if (province) enqueueProvince(province); observer.unobserve(entry.target); } }), { rootMargin: "180px" }); document.querySelectorAll(".province-card").forEach(card => { if (!weatherByProvince.has(card.dataset.provinceId)) observer.observe(card); }); }
  const provinceInput = document.querySelector("#province-search"), provinceGrid = document.querySelector("#province-grid");
  provinceInput.addEventListener("input", event => { provinceQuery = event.target.value.slice(0, 80); drawProvinces(); });
  provinceInput.addEventListener("keydown", event => { const cards = [...provinceGrid.querySelectorAll("[data-province-id]")]; if (event.key === "ArrowDown" && cards.length) { event.preventDefault(); cards[0].focus(); } else if (event.key === "Enter" && cards.length) { event.preventDefault(); cards[0].click(); } });
  provinceGrid.addEventListener("keydown", event => { const cards = [...provinceGrid.querySelectorAll("[data-province-id]")], current = cards.indexOf(event.target.closest("[data-province-id]")); if (current < 0) return; if (event.key === "Escape") { event.preventDefault(); provinceInput.focus(); return; } const columns = Math.max(1, getComputedStyle(provinceGrid).gridTemplateColumns.split(" ").length); const rtl = document.documentElement.dir === "rtl"; const delta = event.key === "ArrowDown" ? columns : event.key === "ArrowUp" ? -columns : event.key === "ArrowRight" ? (rtl ? -1 : 1) : event.key === "ArrowLeft" ? (rtl ? 1 : -1) : 0; if (delta) { event.preventDefault(); cards[Math.max(0, Math.min(cards.length - 1, current + delta))]?.focus(); } });
  provinceGrid.addEventListener("click", event => { const button = event.target.closest("[data-province-id]"); const province = PROVINCES.find(item => item.id === button?.dataset.provinceId); if (province) selectProvince(province); });
  const input = document.querySelector("#global-search"), results = document.querySelector("#global-results"), spinner = document.querySelector(".search-spinner"), searchStatus = document.querySelector("#search-status"); let resultsData = []; let activeIndex = -1; let queryToken = 0, searchController = null;
  function closeResults() { results.hidden = true; results.replaceChildren(); resultsData = []; activeIndex = -1; input.setAttribute("aria-expanded", "false"); input.removeAttribute("aria-activedescendant"); }
  function chooseLocation(place) { if (!validateLocation(place)) return; queryToken++; searchController?.abort(); searchController = null; closeResults(); spinner.classList.remove("active"); searchStatus.textContent = ""; input.value = ""; toggleClear(input); selectedProvince = null; loadPlace(place, null); }
  function setActive(index) { const options = [...results.querySelectorAll('[role="option"]:not([aria-disabled="true"])')]; if (!options.length) return; activeIndex = (index + options.length) % options.length; options.forEach((option, i) => { option.classList.toggle("active", i === activeIndex); option.setAttribute("aria-selected", String(i === activeIndex)); }); input.setAttribute("aria-activedescendant", options[activeIndex].id); options[activeIndex].scrollIntoView({ block: "nearest" }); }
  const search = debounce(async () => { const value = input.value.trim(); const token = ++queryToken; if ([...value].filter(char => char.trim()).length < 2) { closeResults(); spinner.classList.remove("active"); searchStatus.textContent = ""; input.removeAttribute("aria-busy"); return; } spinner.classList.add("active"); input.setAttribute("aria-busy", "true"); searchStatus.textContent = t("searching"); searchController = new AbortController(); const controller = searchController; try { resultsData = await searchLocations(value, currentLanguage, controller.signal); if (token !== queryToken) return; activeIndex = -1; if (resultsData.length) renderSearchResults(results, resultsData, chooseLocation); else { resultsData = []; results.replaceChildren(searchMessage(t("noResults"))); } results.hidden = false; input.setAttribute("aria-expanded", "true"); searchStatus.textContent = resultsData.length ? t("locationsFound")(resultsData.length) : t("noResults"); } catch (error) { if (token !== queryToken) return; resultsData = []; const message = error?.code === "RATE_LIMIT" ? t("rate") : error?.code === "NETWORK" && !navigator.onLine ? t("offline") : t("searchError"); results.replaceChildren(searchMessage(message)); results.hidden = false; input.setAttribute("aria-expanded", "true"); searchStatus.textContent = message; } finally { if (token === queryToken) { spinner.classList.remove("active"); input.removeAttribute("aria-busy"); } if (searchController === controller) searchController = null; } }, WEATHER_CONFIG.SEARCH_DEBOUNCE);
  function cancelSearch() { queryToken++; searchController?.abort(); searchController = null; spinner.classList.remove("active"); input.removeAttribute("aria-busy"); searchStatus.textContent = ""; closeResults(); }
  input.addEventListener("input", () => { queryToken++; searchController?.abort(); searchController = null; input.removeAttribute("aria-busy"); closeResults(); toggleClear(input); const hasQuery = [...input.value.trim()].filter(char => char.trim()).length >= 2; spinner.classList.toggle("active", hasQuery); searchStatus.textContent = ""; if (!hasQuery) spinner.classList.remove("active"); search(); }); input.addEventListener("keydown", event => { if (event.key === "ArrowDown") { event.preventDefault(); setActive(activeIndex + 1); } else if (event.key === "ArrowUp") { event.preventDefault(); setActive(activeIndex < 0 ? 0 : activeIndex - 1); } else if (event.key === "Enter" && !results.hidden && resultsData.length) { event.preventDefault(); chooseLocation(resultsData[activeIndex >= 0 ? activeIndex : 0]); } else if (event.key === "Escape") cancelSearch(); }); document.addEventListener("click", event => { if (!document.querySelector(".global-search").contains(event.target)) cancelSearch(); });
  function searchMessage(message) { const node = document.createElement("div"); node.className = "search-message"; node.setAttribute("role", "option"); node.setAttribute("aria-selected", "false"); node.setAttribute("aria-disabled", "true"); node.textContent = message; return node; }
  function toggleClear(inputNode) { const button = inputNode.parentElement.querySelector(".clear-search"); if (button) button.hidden = !inputNode.value; }
  document.querySelectorAll(".clear-search").forEach(button => button.addEventListener("click", () => { const field = button.parentElement.querySelector("input"); field.value = ""; field.dispatchEvent(new Event("input")); field.focus(); }));
  document.querySelectorAll("[data-lang]").forEach(button => button.addEventListener("click", () => { document.querySelectorAll("[data-lang]").forEach(item => item.setAttribute("aria-pressed", String(item === button))); cancelSearch(); setLanguage(button.dataset.lang); drawProvinces(); if (input.value.trim().length >= 2) search(); }));
  const themeSelect = document.querySelector("#theme-select"); function applyTheme(value) { const preference = ["system", "light", "dark"].includes(value) ? value : "system"; themeSelect.value = preference; storageSet("weather-theme", preference); document.documentElement.dataset.theme = preference === "system" ? (matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light") : preference; } themeSelect.addEventListener("change", () => applyTheme(themeSelect.value)); matchMedia("(prefers-color-scheme: dark)").addEventListener?.("change", () => { if (themeSelect.value === "system") applyTheme("system"); });
  const locateButton = document.querySelector("#locate-button"); let locationPermissionDenied = false, locationRequestPending = false;
  locateButton.addEventListener("click", async () => { if (!navigator.geolocation || locationPermissionDenied || locationRequestPending) { setStatus(t("myLocationError"), "error"); return; } locationRequestPending = true; locateButton.disabled = true; locateButton.setAttribute("aria-busy", "true"); try { const permission = await navigator.permissions?.query?.({ name: "geolocation" }); if (permission?.state === "denied") { locationPermissionDenied = true; setStatus(t("myLocationError"), "error"); locationRequestPending = false; locateButton.disabled = false; locateButton.removeAttribute("aria-busy"); return; } } catch { /* The Permissions API is optional; geolocation still handles the decision. */ } const finish = () => { locationRequestPending = false; locateButton.disabled = false; locateButton.removeAttribute("aria-busy"); }; try { navigator.geolocation.getCurrentPosition(position => { finish(); const latitude = position.coords.latitude, longitude = position.coords.longitude; if (!validCoordinates(latitude, longitude)) { setStatus(t("myLocationError"), "error"); return; } const place = { name: t("myLocation"), country: "", region: "", timezone: "UTC", latitude, longitude }; selectedProvince = null; loadPlace(place, null); }, error => { finish(); if (error?.code === 1) locationPermissionDenied = true; setStatus(t("myLocationError"), "error"); }, { timeout: 10000, maximumAge: 300000 }); } catch { finish(); setStatus(t("myLocationError"), "error"); } });
  document.addEventListener("languagechange", () => { if (activeData) renderWeather(activeData, selectedProvince || selectedPlace); else renderWeatherLoading(selectedProvince || selectedPlace); drawProvinces(); });
  setLanguage(storageGet("weather-language") || "en"); applyTheme(storageGet("weather-theme") || "system"); drawProvinces(); let restored = null; try { restored = JSON.parse(storageGet("weather-location") || "null"); } catch { } if (restored && validCoordinates(restored.latitude, restored.longitude) && typeof restored.name === "string" && restored.name.trim()) { selectedPlace = { name: restored.name.trim().slice(0, 120), country: typeof restored.country === "string" ? restored.country.slice(0, 100) : "", region: typeof restored.region === "string" ? restored.region.slice(0, 100) : "", timezone: validTimezone(restored.timezone) ? restored.timezone : "UTC", latitude: restored.latitude, longitude: restored.longitude, id: typeof restored.id === "string" ? restored.id : null }; selectedProvince = PROVINCES.find(item => item.id === selectedPlace.id) || null; } loadPlace(selectedPlace, selectedProvince);
  setInterval(() => { if (activeData) document.querySelector("#local-clock").textContent = formatLocalTime(new Date().toISOString(), activeData.timezone); }, 30000);
})();
