const I18N = {
    en: { brand: "Weather Afghanistan", tagline: "Weather across every province", provinceSearch: "Find an Afghan province…", globalSearch: "Search cities worldwide…", provinces: "Afghanistan provinces", world: "World search", locate: "Use my location", theme: "Appearance", themeSystem: "System", themeLight: "Light", themeDark: "Dark", today: "Today", feels: "Feels like", high: "H", low: "L", observed: "Updated", hourly: "Next 24 hours", daily: "7-day forecast", details: "Weather details", humidity: "Humidity", wind: "Wind", pressure: "Pressure", visibility: "Visibility", cloud: "Cloud cover", uv: "UV index", sunrise: "Sunrise", sunset: "Sunset", across: "Weather across Afghanistan", all34: "All 34 provinces", mapTitle: "Afghanistan map", mapNote: "Province-boundary map data is not available in this lightweight edition.", loading: "Loading weather…", offline: "No internet connection. Please check your connection and try again.", apiError: "Weather data is temporarily unavailable. Please try again.", rate: "The weather service is busy. Please try again shortly.", notFound: "Location not found.", noData: "Weather data is not available.", searching: "Searching…", noResults: "No locations found.", searchError: "Location search is temporarily unavailable.", stale: "Showing saved weather data; it may be outdated.", country: "Afghanistan", emptyProvince: "No matching province found.", dataSource: "Weather data by Open-Meteo", privacy: "About & privacy", footer: "Built for weather across Afghanistan", day: "Today", night: "Night", clear: "Clear", clearNight: "Clear night", partlyCloudy: "Partly cloudy", cloudy: "Cloudy", fog: "Fog", drizzle: "Drizzle", rain: "Rain", heavyRain: "Heavy rain", snow: "Snow", thunderstorm: "Thunderstorm", unknown: "Conditions unavailable", windUnit: "km/h", visibilityUnit: "km", pressureUnit: "hPa", loadingProvinces: "Province weather loads gradually as you browse.", myLocationError: "Could not access your location. You can still search for a place.", forecastEmpty: "Forecast unavailable", noTemperature: "—", language: "Language", forecastLabel: "Forecast", outlookLabel: "Outlook", glanceLabel: "At a glance", geography: "Geography", countryLabel: "Afghanistan", clearSearch: "Clear search", locateAria: "Use my location", searchResults: "Location search results" },
    fa: { brand: "هواشناسی افغانستان", tagline: "آب‌وهوا در سراسر ولایت‌ها", provinceSearch: "جستجوی ولایت افغانستان…", globalSearch: "جستجوی شهر در جهان…", provinces: "ولایت‌های افغانستان", world: "جستجوی جهان", locate: "موقعیت من", theme: "نمایش", themeSystem: "سیستم", themeLight: "روشن", themeDark: "تاریک", today: "امروز", feels: "حس‌شده", high: "ب", low: "ک", observed: "به‌روزرسانی", hourly: "۲۴ ساعت آینده", daily: "پیش‌بینی ۷ روزه", details: "جزئیات هوا", humidity: "رطوبت", wind: "سرعت باد", pressure: "فشار هوا", visibility: "دید", cloud: "پوشش ابر", uv: "شاخص UV", sunrise: "طلوع آفتاب", sunset: "غروب آفتاب", across: "آب‌وهوای ۳۴ ولایت افغانستان", all34: "هر ۳۴ ولایت", mapTitle: "نقشه افغانستان", mapNote: "دادهٔ مرز ولایت‌ها در این نسخهٔ سبک در دسترس نیست.", loading: "در حال دریافت وضعیت هوا…", offline: "اتصال اینترنت برقرار نیست. لطفاً اتصال خود را بررسی کرده و دوباره تلاش کنید.", apiError: "اطلاعات هوا موقتاً در دسترس نیست. لطفاً دوباره تلاش کنید.", rate: "سرویس هواشناسی شلوغ است. کمی بعد دوباره تلاش کنید.", notFound: "موقعیت پیدا نشد.", noData: "اطلاعات هوا در دسترس نیست.", searching: "در حال جستجو…", noResults: "موقعیتی پیدا نشد.", searchError: "جستجوی موقعیت موقتاً در دسترس نیست.", stale: "اطلاعات ذخیره‌شده نمایش داده می‌شود؛ ممکن است تازه نباشد.", country: "افغانستان", emptyProvince: "ولایتی پیدا نشد.", dataSource: "داده‌های هواشناسی از Open-Meteo", privacy: "درباره و حریم خصوصی", footer: "برای آب‌وهوای افغانستان", day: "امروز", night: "شب", clear: "صاف", clearNight: "شب صاف", partlyCloudy: "نیمه‌ابری", cloudy: "ابری", fog: "مه", drizzle: "نم‌نم باران", rain: "باران", heavyRain: "باران شدید", snow: "برف", thunderstorm: "رعد و برق", unknown: "وضعیت نامشخص", windUnit: "کیلومتر در ساعت", visibilityUnit: "کیلومتر", pressureUnit: "هکتوپاسکال", loadingProvinces: "وضعیت ولایت‌ها هنگام مرور به‌تدریج دریافت می‌شود.", myLocationError: "دسترسی به موقعیت ممکن نشد. می‌توانید نام مکان را جستجو کنید.", forecastEmpty: "پیش‌بینی در دسترس نیست", noTemperature: "—", language: "زبان", forecastLabel: "پیش‌بینی", outlookLabel: "چشم‌انداز", glanceLabel: "نمای کلی", geography: "جغرافیا", countryLabel: "افغانستان", clearSearch: "پاک کردن جستجو", locateAria: "استفاده از موقعیت من", searchResults: "نتایج جستجوی موقعیت" }
};
I18N.en.pageTitle = "Weather Afghanistan — Weather for All 34 Provinces"; I18N.fa.pageTitle = "آب‌وهوای افغانستان — آب‌وهوای ۳۴ ولایت"; I18N.en.myLocation = "My location"; I18N.fa.myLocation = "موقعیت من"; I18N.en.brandHome = "Weather Afghanistan home"; I18N.fa.brandHome = "صفحهٔ اصلی هواشناسی افغانستان"; I18N.en.headerTools = "Weather tools"; I18N.fa.headerTools = "ابزارهای هواشناسی"; I18N.en.currentWeather = "Current weather"; I18N.fa.currentWeather = "وضعیت فعلی هوا"; I18N.en.privacyPolicy="Privacy policy";I18N.fa.privacyPolicy="سیاست حریم خصوصی";I18N.en.termsLink="Terms";I18N.fa.termsLink="شرایط استفاده";I18N.en.cookiePolicy="Cookie policy";I18N.fa.cookiePolicy="سیاست کوکی‌ها";I18N.en.dataUse="Data use";I18N.fa.dataUse="استفاده از داده‌ها";
I18N.en.aboutDeveloper = "About the Developer";
I18N.fa.aboutDeveloper = "دربارهٔ توسعه‌دهنده";
I18N.en.creatorName = "Erfanullah Esmati";
I18N.fa.creatorName = "عرفان‌الله عصمتی";
I18N.en.creatorRole = "Web Developer & Future Cybersecurity Specialist";
I18N.fa.creatorRole = "توسعه‌دهندهٔ وب و متخصص آیندهٔ امنیت سایبری";
I18N.en.creatorBio = "I’m a software developer from Afghanistan focused on building practical, modern, and secure digital solutions. My interests include web development, networking, Linux, and cybersecurity, with a long-term focus on becoming a cybersecurity specialist.";
I18N.fa.creatorBio = "من توسعه‌دهندهٔ نرم‌افزار از افغانستان هستم و بر ساخت راهکارهای دیجیتال کاربردی، مدرن و امن تمرکز دارم. به توسعهٔ وب، شبکه، لینوکس و امنیت سایبری علاقه‌مندم و در درازمدت می‌خواهم در زمینهٔ امنیت سایبری تخصص پیدا کنم.";
I18N.en.locationsFound = count => `${count} locations found.`;
I18N.fa.locationsFound = count => `${count} موقعیت پیدا شد.`;
I18N.en.partlyCloudyNight = "Partly cloudy night";
I18N.fa.partlyCloudyNight = "شب نیمه‌ابری";
I18N.en.provinceError = "Unavailable";
I18N.fa.provinceError = "در دسترس نیست";
const CONDITION_KEY = { clear: "clear", "clear-night": "clearNight", "partly-cloudy": "partlyCloudy", "partly-cloudy-night": "partlyCloudyNight", cloudy: "cloudy", fog: "fog", drizzle: "drizzle", rain: "rain", "heavy-rain": "heavyRain", snow: "snow", thunderstorm: "thunderstorm", unknown: "unknown" };
let currentLanguage = "en"; let currentWeather = null; let currentPlace = null;
function storageGet(key) { try { return localStorage.getItem(key) } catch { return null } } function storageSet(key, value) { try { localStorage.setItem(key, value) } catch { } }
function t(key) { return I18N[currentLanguage][key] ?? I18N.en[key] ?? key; }
function setLanguage(language) { currentLanguage = language === "fa" ? "fa" : "en"; storageSet("weather-language", currentLanguage); document.documentElement.lang = currentLanguage === "fa" ? "fa-AF" : "en"; document.documentElement.dir = currentLanguage === "fa" ? "rtl" : "ltr"; document.title = t("pageTitle"); document.querySelectorAll("[data-i18n]").forEach(el => el.textContent = t(el.dataset.i18n)); document.querySelectorAll("[data-placeholder]").forEach(el => el.placeholder = t(el.dataset.placeholder)); document.querySelector(".brand")?.setAttribute("aria-label",t("brandHome"));document.querySelector(".header-tools")?.setAttribute("aria-label",t("headerTools"));document.querySelector(".weather-hero")?.setAttribute("aria-label",t("currentWeather"));document.querySelector(".language-switch")?.setAttribute("aria-label",t("language"));document.querySelector("#global-results")?.setAttribute("aria-label",t("searchResults"));document.querySelectorAll(".clear-search").forEach(button=>button.setAttribute("aria-label",t("clearSearch")));document.querySelector("#locate-button")?.setAttribute("aria-label",t("locateAria"));document.querySelector("#theme-select")?.setAttribute("aria-label",t("theme"));if(!currentWeather)text("#place-subtitle",t("country"));document.dispatchEvent(new CustomEvent("languagechange")); if (currentWeather) renderWeather(currentWeather, currentPlace); }
function formatNumber(value, digits = 0) { if (typeof value !== "number" || !Number.isFinite(value)) return "—"; return new Intl.NumberFormat(currentLanguage === "fa" ? "fa-AF-u-nu-latn" : "en", { maximumFractionDigits: digits }).format(value); }
function formatTemp(value) { return typeof value === "number" && Number.isFinite(value) ? `${formatNumber(Math.round(value))}°` : "—"; }
function formatLocalTime(iso, timezone = currentWeather?.timezone) { if (!iso) return "—"; try { const locale = currentLanguage === "fa" ? "fa-AF-u-nu-latn" : "en"; if (typeof iso === "string" && !/[zZ]|[+-]\d\d:\d\d$/.test(iso)) { const match = iso.match(/T(\d{2}):(\d{2})/); if (!match) return "—"; const wallClock = new Date(Date.UTC(2020, 0, 1, Number(match[1]), Number(match[2]))); return new Intl.DateTimeFormat(locale, { hour: "numeric", minute: "2-digit", timeZone: "UTC" }).format(wallClock); } return new Intl.DateTimeFormat(locale, { hour: "numeric", minute: "2-digit", timeZone: timezone || "UTC" }).format(new Date(iso)); } catch { return "—"; } }
function weatherIcon(condition, size = 30) {
    const assets = { clear:"clear.svg", "clear-night":"clear-night.svg", "partly-cloudy":"partly-cloudy.svg", "partly-cloudy-night":"partly-cloudy-night.svg", cloudy:"cloudy.svg", fog:"fog.svg", drizzle:"drizzle.svg", rain:"rain.svg", "heavy-rain":"heavy-rain.svg", snow:"snow.svg", thunderstorm:"thunderstorm.svg", unknown:"cloudy.svg" };
    const icon = document.createElement("img"); icon.className = "weather-svg"; icon.src = `assets/icons/${assets[condition] || assets.unknown}`; icon.width = size; icon.height = size; icon.alt = ""; icon.setAttribute("aria-hidden", "true"); icon.decoding = "async"; return icon;
}
function conditionName(condition) { return t(CONDITION_KEY[condition] || "unknown"); }
function renderWeatherLoading(place) { currentWeather = null; currentPlace = place; const title = currentLanguage === "fa" ? (place?.nameFa || place?.name || "کابل") : (place?.nameEn || place?.name || "Kabul"); text("#place-name", title); text("#place-subtitle", [place?.region, place?.country].filter(Boolean).join(" · ") || t("country")); text("#condition", t("loading")); text("#temperature", "—"); text("#feels", `${t("feels")} —`); text("#range", `${t("high")} — · ${t("low")} —`); text("#hero-icon", ""); document.querySelector("#hero-icon")?.setAttribute("aria-label", t("loading")); text("#updated", ""); text("#local-clock", ""); document.querySelectorAll("[data-metric]").forEach(el => { el.closest(".metric")?.classList.add("is-unavailable"); textNode(el, "—"); }); document.querySelector("#hourly-list")?.replaceChildren(emptyRow(t("loading"))); document.querySelector("#daily-list")?.replaceChildren(emptyRow(t("loading"))); document.documentElement.dataset.weather = "unknown"; renderWeatherEffects("unknown"); }
function renderWeatherUnavailable() { text("#condition", t("noData")); text("#updated", ""); document.querySelector("#hourly-list")?.replaceChildren(emptyRow(t("forecastEmpty"))); document.querySelector("#daily-list")?.replaceChildren(emptyRow(t("forecastEmpty"))); }
function renderWeather(data, place, { stale = false } = {}) {
    currentWeather = data; currentPlace = place; const night = localIsNight(data); const condition = getWeatherCondition(data.current.weatherCode, night); document.documentElement.dataset.weather = condition;document.querySelector("#hero-icon")?.setAttribute("aria-label",getWeatherDescription(data.current.weatherCode,currentLanguage));
    const title = currentLanguage === "fa" ? (place?.nameFa || place?.name || data.locationName || "کابل") : (place?.nameEn || place?.name || data.locationName || "Kabul"); text("#place-name", title); const sub = [place?.region, place?.country || (place?.id ? t("country") : "")].filter(Boolean).join(" · "); text("#place-subtitle", sub); text("#condition", getWeatherDescription(data.current.weatherCode, currentLanguage)); text("#temperature", formatTemp(data.current.temperature)); text("#feels", `${t("feels")} ${formatTemp(data.current.feelsLike)}`); const today = data.daily.find(item => item.date === data.current.time.slice(0, 10)) || data.daily[0]; text("#range", `${t("high")} ${formatTemp(today?.high)}  ·  ${t("low")} ${formatTemp(today?.low)}`); document.querySelector("#hero-icon").replaceChildren(weatherIcon(condition, 72)); text("#updated", `${stale ? `${t("stale")} · ` : ""}${t("observed")} ${formatLocalTime(data.current.time)}`); text("#local-clock", formatLocalTime(new Date().toISOString()));
    const metrics = { humidity: data.current.humidity == null ? null : `${formatNumber(data.current.humidity)}%`, wind: data.current.windSpeed == null ? null : `${formatNumber(data.current.windSpeed)} ${t("windUnit")}${data.current.windDirection == null ? "" : ` · ${formatNumber(data.current.windDirection)}°`}`, pressure: data.current.pressure == null ? null : `${formatNumber(data.current.pressure)} ${t("pressureUnit")}`, visibility: data.current.visibility == null ? null : `${formatNumber(data.current.visibility / 1000, 1)} ${t("visibilityUnit")}`, cloud: data.current.cloudCover == null ? null : `${formatNumber(data.current.cloudCover)}%`, uv: today?.uvIndex == null ? null : formatNumber(today.uvIndex, 1), sunrise: today?.sunrise ? formatLocalTime(today.sunrise) : null, sunset: today?.sunset ? formatLocalTime(today.sunset) : null }; document.querySelectorAll("[data-metric]").forEach(el => { const value = metrics[el.dataset.metric]; el.closest(".metric")?.classList.toggle("is-unavailable", value == null); textNode(el, value ?? "—"); });
    renderHourly(data); renderDaily(data); renderWeatherEffects(condition);
}
function nightAt(data,time){const day=data.daily.find(item=>item.date===time.slice(0,10));return day?.sunrise&&day?.sunset?(time<day.sunrise||time>=day.sunset):false;}
function renderHourly(data) { const list = document.querySelector("#hourly-list"); list.replaceChildren(); const hourly = data.hourly.filter(item => item.time >= data.current.time).slice(0, 24); for (const item of hourly) { const li = document.createElement("li"); li.className = "hour-item"; const time = document.createElement("span"); time.textContent = formatLocalTime(item.time); const condition=getWeatherCondition(item.weatherCode,nightAt(data,item.time));const icon = weatherIcon(condition, 27); const temp = document.createElement("strong"); temp.textContent = formatTemp(item.temperature); const desc = document.createElement("span"); desc.textContent = conditionName(condition); li.append(time, icon, temp, desc); list.append(li); } if (!hourly.length) list.append(emptyRow(t("forecastEmpty"))); }
function renderDaily(data) { const list = document.querySelector("#daily-list"); list.replaceChildren(); data.daily.slice(0, 7).forEach((day, index) => { const li = document.createElement("li"); li.className = "daily-row"; const date = document.createElement("span"); date.className = "daily-date"; date.textContent = index === 0 ? t("today") : new Intl.DateTimeFormat(currentLanguage === "fa" ? "fa-AF-u-nu-latn" : "en", { weekday: "long", timeZone: "UTC" }).format(new Date(`${day.date}T12:00:00Z`)); const icon = weatherIcon(getWeatherCondition(day.weatherCode, false), 28); const desc = document.createElement("span"); desc.className = "daily-condition"; desc.textContent = conditionName(getWeatherCondition(day.weatherCode, false)); const temps = document.createElement("strong"); temps.textContent = `${formatTemp(day.high)} / ${formatTemp(day.low)}`; li.append(date, icon, desc, temps); list.append(li); }); if (!data.daily.length) list.append(emptyRow(t("forecastEmpty"))); }
function renderWeatherEffects(condition) { const root = document.querySelector("#weatherEffects"); root.replaceChildren(); if (matchMedia("(prefers-reduced-motion: reduce)").matches) return; const fragment = document.createDocumentFragment(); if (condition === "clear" || condition === "partly-cloudy") createSun(fragment); if (condition === "clear-night" || condition === "partly-cloudy-night") { createStars(fragment); createMoon(fragment); } if (["partly-cloudy", "partly-cloudy-night", "cloudy", "rain", "drizzle", "heavy-rain", "thunderstorm"].includes(condition)) createClouds(fragment, condition === "partly-cloudy" || condition === "partly-cloudy-night" ? 1 : condition === "cloudy" ? 2 : 3); if (["rain", "drizzle", "heavy-rain", "thunderstorm"].includes(condition)) createRain(fragment, condition === "heavy-rain" || condition === "thunderstorm" ? 32 : condition === "drizzle" ? 12 : 22); if (condition === "snow") createSnow(fragment, 24); if (condition === "fog") createFog(fragment); if (condition === "thunderstorm") createLightning(fragment); root.append(fragment); }
function createClouds(container, amount) { for (let i = 0; i < amount; i++) { const cloud = document.createElement("i"); cloud.className = `cloud-particle cloud-${i + 1}`; container.append(cloud); } }
function createRain(container, amount) { for (let i = 0; i < amount; i++) { const particle = document.createElement("i"); particle.className = i % 3 === 0 ? "rain-particle rain-particle--near" : "rain-particle"; particle.style.setProperty("--x", `${Math.random() * 100}%`); particle.style.setProperty("--delay", `${-Math.random() * 2.4}s`); particle.style.setProperty("--duration", `${.65 + Math.random() * .9}s`); particle.style.setProperty("--length", `${18 + Math.random() * 26}px`); particle.style.setProperty("--thickness", `${i % 3 === 0 ? 1.5 : 1}px`); container.append(particle); } }
function createSnow(container, amount) { for (let i = 0; i < amount; i++) { const particle = document.createElement("i"); particle.className = "snow-particle"; particle.style.setProperty("--x", `${Math.random() * 100}%`); particle.style.setProperty("--delay", `${-Math.random() * 12}s`); particle.style.setProperty("--duration", `${7 + Math.random() * 9}s`); particle.style.setProperty("--size", `${3 + Math.random() * 5}px`); particle.style.setProperty("--drift", `${-28 + Math.random() * 56}px`); particle.style.opacity = String(.48 + Math.random() * .5); container.append(particle); } }
function createSun(container) { const sun = document.createElement("i"); sun.className = "sun-effect"; container.append(sun); }
function createMoon(container) { const moon = document.createElement("i"); moon.className = "moon-effect"; container.append(moon); }
function createStars(container) { for (let i = 0; i < 22; i++) { const star = document.createElement("i"); star.className = "star-particle"; star.style.setProperty("--x", `${Math.random() * 100}%`); star.style.setProperty("--y", `${Math.random() * 58}%`); star.style.setProperty("--delay", `${Math.random() * 5}s`); container.append(star); } }
function createFog(container) { const fog = document.createElement("i"); fog.className = "fog-effect"; container.append(fog); }
function createLightning(container) { const lightning = document.createElement("i"); lightning.className = "lightning-effect"; container.append(lightning); }
function setStatus(message, state = "info") { const box = document.querySelector("#status"); box.hidden = !message; box.dataset.state = state; text("#status", message); }
function text(selector, value) { const node = document.querySelector(selector); if (node) node.textContent = String(value ?? ""); } function textNode(node, value) { node.textContent = String(value ?? ""); } function emptyRow(message) { const li = document.createElement("li"); li.className = "empty-row"; li.textContent = message; return li; }
function renderProvinceCards(filter = "", weatherMap = new Map(), selectedId = "kabul") { const root = document.querySelector("#province-grid"); root.replaceChildren(); const query = filter.trim().toLocaleLowerCase(); const results = PROVINCES.filter(p => `${p.nameEn} ${p.nameFa} ${p.capital}`.toLocaleLowerCase().includes(query)); for (const province of results) { const button = document.createElement("button"); button.className = "province-card"; button.type = "button"; button.dataset.provinceId = province.id; button.setAttribute("aria-pressed", String(province.id === selectedId)); if (province.id === selectedId) button.classList.add("selected"); const title = document.createElement("span"); title.className = "province-card-name"; title.textContent = currentLanguage === "fa" ? province.nameFa : province.nameEn; const cap = document.createElement("span"); cap.className = "province-card-capital"; cap.textContent = province.capital; const result = weatherMap.get(province.id); const meta = document.createElement("span"); meta.className = "province-card-weather"; if (result?.error) { const unavailable = document.createElement("small"); unavailable.textContent = t("provinceError"); meta.append(unavailable); } else if (result) { meta.append(weatherIcon(getWeatherCondition(result.current.weatherCode, localIsNight(result)), 24)); const temp = document.createElement("strong"); temp.textContent = formatTemp(result.current.temperature); const cond = document.createElement("small"); cond.textContent = getWeatherDescription(result.current.weatherCode, currentLanguage); meta.append(temp, cond); } else { const loading = document.createElement("small"); loading.textContent = t("loading"); meta.append(loading); } button.append(title, cap, meta); root.append(button); } if (!results.length) root.append(emptyRow(t("emptyProvince"))); }
function renderSearchResults(root, items, choose) { root.replaceChildren(); items.forEach((item, index) => { const option = document.createElement("div"); option.setAttribute("role", "option"); option.setAttribute("aria-selected", "false"); option.id = `location-option-${index}`; option.className = "search-result"; const name = document.createElement("strong"); name.textContent = item.name; const meta = document.createElement("span"); meta.textContent = [item.region, item.country].filter(Boolean).join(", "); option.append(name, meta); option.addEventListener("click", () => choose(item)); root.append(option); }); }
